version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: insightfusion-postgres
    environment:
      POSTGRES_USER: admin 
      POSTGRES_PASSWORD: admin 
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant
    container_name: insightfusion-qdrant
    ports:
      - "6333:6333"
    